name: bigdomains_import
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Alex Vasiliev <alex@mdi-toys.ru>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.0
  postgres: ^1.0.2
  csv: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
